# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:icecream_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# H2 Console (http://localhost:8080/h2-console)
spring.h2.console.enabled=true

# JSON
spring.jackson.serialization.write-dates-as-timestamps=false
